### ISSUE TITLE
eval问题

### ISSUE THREAD

**Issue by xiaoding06** [tangjielong928/mqspn#3]
<img width="573" alt="18ecfb9975ae29a381da2106807f6d0" src="https://github.com/user-attachments/assets/54a56a00-c69a-4966-a03c-134505e1e623">
<img width="281" alt="96ab9e56869167ce78995169c025bce" src="https://github.com/user-attachments/assets/29243fe5-d2e0-4724-a81e-1183c79daedf">
<img width="611" alt="430f9f0c0e14c03729b70f7fbf56027" src="https://github.com/user-attachments/assets/c65099a2-29b8-4e5d-a92f-28e11735abc3">
您好，就是在运行eval文件的时候不是会保存一个路径吗data/checkpoints，我运行完50个epoch后想去做eval可是这个checkpoints文件打不开，不知道什么原因报这个错误，想问问您运行的时候有过这个错误嘛，是在服务器上面跑的代码，想去评估得把 # checkpoint_path = data/checkpoints/twitter10k/twitter10k_train/best_0806/best_model/best_model.pth设置为您注释的这样子的路径，可是重新运行好几次还是打不开checkpoints，可以帮忙看看嘛，谢谢您。

**Comment by tangjielong928** [comment]
@xiaoding06 checkpoint_path为你最后输出文件的best_model.pth文件路径，看你的截图貌似是放的directory？例如我的是在data/checkpoints/twitterGMNER/twitter10k_train/best_0806/best_model/best_model.pth，如果还遇到问题请提供您eval的config详细截图以及完整报错log

**Comment by tangjielong928** [comment]
@xiaoding06 
![02a01a131f2813df875696bd895a4f8](https://github.com/user-attachments/assets/cce6ad6d-2fd1-4659-bdec-2b5c0d27749a)
您可能的checkpoints路径见上图

**Comment by xiaoding06** [comment]
<img width="626" alt="e8331a83251f4e3bc5186f4d8bfc972" src="https://github.com/user-attachments/assets/da57950f-feb8-4847-9fda-143e595d19ea">
您好后面通过命令行的方式查询到了best_model.pth路径，就复制到了checkpoint_path然后进行eval，这是昨天eval跑出来的结果，辛苦您啦，特别感谢您的回复
